### PR TITLE
Add recipe form

### PR DESCRIPTION
**Pull request by AbdallahSafar**

### CODE REVIEW

**Comment by osamaakb** [comment]
@AbdallahSafar Where is the test code and the output image?

**Comment by osamaakb** [comment]
Good job @AbdallahSafar ,
The design looks nice, however, we can improve it more, 
- The `select image` button should say something else after you select an image like `change image` 

image
- The categories don't look that great, you can make them a multi-select dropdown, check out this tutorial here- 
https://dev.to/hunterjsbit/build-multiselect-component-in-react-in-few-lines-4m1c

- details input should be at the end and make it's hight less
- I suggest the ingredients be multiple inputs one under the other one and a button under the last one that says `add more ingredients`, maybe add 3 inputs at the beginning and if the user wants more he can click the `add` button
because the current one-input way doesn't look that clear.
- same for the directions input, maybe have 3 inputs as a start and a button to let the user add more directions

let me know if any of this doesn't sound clear or good

**Comment by AbdallahSafar** [comment]
Screenshot (424)
Screenshot (425)
@osamaakb I pushed the code with a console.log to let you see the bug. Please test it and take a look on the categories input, if you chose 2 categories (e.g. Fruit, breakfast) only 'fruit' will be inserted in the categories property of the useState.

**Comment by osamaakb** [comment]
@AbdallahSafar please take a look now, I fixed the categories issue, it wasn't updating the recipe state because the `selectedItems` aren't updated yet, so I created a new variable with the new item and added it to the recipe state

**Comment by AbdallahSafar** [comment]
@osamaakb I saw the variable but `setSelected(prevState => [...prevState, item]);` this one in line 19 isn't updating the selectedItems already?

**Review by osamaakb — APPROVED** [review]

**Pull request merged**
