### PR TITLE
Added on category click feature to change color

### PR DESCRIPTION
**Pull request by Adnan-961**

### CODE REVIEW

**Comment by osamaakb** [comment]
please fix the conflicts and provide description and output image to the result

**Comment by osamaakb** [comment]
@Adnan-961 any idea when you will finish this one?

**Comment by Adnan-961** [comment]
hey @osamaakb , Fixed

**Comment by osamaakb** [comment]
where is the description and output image? please read my comment very well

**Review by osamaakb — APPROVED** [review]

**Pull request merged**
